### ISSUE TITLE
Spider's wares are off

### ISSUE THREAD

**Issue by errera** [justrealmilk/dev2.braytech.org#28]
Haven't checked other vendors, but Spider's offerings are off. It's not the API (I don't think) - DIM's got 'em right. I THINK (but could be utterly wrong) that the problem might have to do with you trusting the reset numbers. :) (That is - they say they reset in 3 days (well, they've said since Tuesday morning that they'll reset next Tuesday), so maybe you're not checking after the weekly reset? They definitely change more often than that, even though they say they don't.)

**Comment by justrealmilk** [comment]
The vendors endpoint is a very dramatic place filled with drama. Vendors personalities literally come alive outside the game. I refresh once at 3:02 AM just reset (hard to debug since I'm usually asleep). 

I've noticed this for Spider as well and I feel like I can't trust my own site which sucks. So I'll look into it.

As for DIM - it checks on the spot using your own character whereas I cache the response for the day

**Comment by errera** [comment]
Ah - the 'check on my own character vs cache once per day' makes total sense. (Spider's right right now, fwiw.) Ah, well. Minor issue - the site is looking fantastic!

**Comment by justrealmilk** [comment]
increased update frequency
